project:
  type: website

website:
  title: "Aaron R. Williams"
  site-url: https://aaronrwilliams.com
  description: "Data Science for Public Policy"
  navbar:
    left:
      - about.qmd
      - blog.qmd
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
execute:
  freeze: auto        
format:
  html:
    theme: minty
    css: styles.css



