project:
  type: website

website:
  title: "Aaron R. Williams"
  site-url: https://aaronrwilliams.com
  description: "Data Science for Public Policy"
  navbar:
    left:
      - about.qmd
      - cv.qmd
      - teaching.qmd
      - blog.qmd
    right:
      - icon: github
        href: https://github.com/awunderground
      - icon: twitter
        href: https://twitter.com/awunderground
      - icon: LinkedIn
        href: https://www.linkedin.com/in/aaronrwilliams100/        
format:
  html:
    theme: minty
    css: styles.css



