project:
  type: website
  render:
    - "index.qmd"
    - "about.qmd"
    - "cv.qmd"
    - "workshops.qmd"
    - "blog/blog.qmd"
    - "blog/**/*.qmd"
    - "talks/talk.qmd"
    - "talks/**/*.qmd"

website:
  title: "Aaron R. Williams"
  site-url: https://aaronrwilliams.com
  description: "Data Science for Public Policy"
  navbar:
    left:
      - about.qmd
      - cv.qmd
      - workshops.qmd
      - blog/blog.qmd
    right:
      - icon: github
        href: https://github.com/awunderground
      - icon: LinkedIn
        href: https://www.linkedin.com/in/aaronrwilliams100/        
format:
  html:
    theme: minty
    toc: true
    link-external-newwindow: true
    css: styles.scss

editor: source

execute:
  freeze: auto