---
title: "Workshops"
---

## What I Offer

I offer on-site, hybrid, and virtual half-, full-, and multi-day workshops about R, data visualization, data science, and statistics. Workshop attendees will learn practical data skills that will improve the quality of their work and build their confidence with technical tools like programming. _All workshops and workshop examples can be adjusted to meet the specific needs of your organization._

Workshops are designed around hands-on examples that demonstrate theory and practice. Attendees will understand the _why_ and the _how_ of approaching analytic problems with the data science toolkit.  

I bring my experience as a data scientist to your data. We won’t just copy and paste code until a sensible answer appears. We will work to understand each decision so that attendees leave prepared to tackle questions that haven’t been asked and problems that haven’t yet appeared.  

## Teaching Experience

- 10 semesters teaching graduate students in the [McCourt School of Public Policy](https://mccourt.georgetown.edu/)
- 16 traveling courses through the [American Statistical Association's Council of Chapters Traveling Courses](https://community.amstat.org/coc/chapterresources/travelingcourse)
- Short courses at the Joint Statistical Meetings (Toronto, Canada and Portland, OR), Symposium on Data Science and Statistics (Pittsburgh, PA), and International Conference on Establishment Statistics (Glasgow, Scotland)
- Half- and full-day courses around the world and across the country with [PolicyViz](https://policyviz.com/#1612198666662-767a3ef9-d28e)

## Typical Workshops

_All workshops and workshop examples can be adjusted to meet the specific needs of your organization._

### Introduction to R

In this workshop, attendees will install and open R, learn the basic code structure and syntax, and conduct hands-on analysis of real data. This workshop will outline specific methods for project organization, data management, summary statistics, and data visualizations. Attendees will have ample opportunities to put this knowledge to work with hands-on examples.  

### Data Visualization in R 

R is known for its ability to efficiently and effectively visualize data. In this workshop, attendees will learn a comprehensive set of tools for programmatically creating static data visualizations in R using a package called ggplot2. The workshop will teach the theory, called the “grammar of graphics”, behind ggplot2. From this theory, attendees will learn to code data visualization in R. Learning the theory and the code will help attendees build better data visualizations, understand how the components of a data visualization come together, and master and retain ggplot2. 

### Creating R Tools for Organizations 

Organizations can create value by leveraging the power of R at an institutional level. This workshop will introduce and outline how tools like R packages, R markdown, R Shiny, and ggplot2 can be used by organizations to find new insights, consistently communicate their findings, and use programming to get rid of mundane and repetitive tasks. Approaches include creating custom tools and R packages to increase productivity, designing custom ggplot2 themes that match organizational branding, and creating documents and applications that can be used to regularly generate reports. Attendees will leave understanding how R can be used at the organizational level and how to get started building tools for their organization.  

## Other Details 

I will send data and code files to attendees prior to the workshop. These materials will be sent via email and a shared cloud-based storage service such as Google Drive or Dropbox. 
