---
title: "I used to blog"
author: "Aaron R Williams"
date: 2018-10-29
categories: ["R"]
tags: ["R Markdown", "housekeeping"]
---

I used to blog. I blogged about [jazz](https://rvanews.com/tag/jazz). I blogged about [VCU basketball](https://rvanews.com/tag/rams). I blogged about [trying to make RVA a better place](https://rvanews.com/tag/100-days-rva) and about [public policy in Virginia](http://thehalfsheet.org/). 

Blogging was how I learned to write. Blogging was how I learned about VCU basketball. It's how I learned about Medicaid expansion and school funding formulas. Blogging was how I learned. 

Then, I stopped blogging. 

A few months ago, my colleagues Ben Chartoff, [Graham MacDonald](http://www.grahamimac.com/), and [Jon Schwabish](https://policyviz.com/) asked me to contribute to [Data@Urban](https://medium.com/@urban_institute). Contributing is one of the highlights of my 2018, so I decided to launch a blog using Yihui Xie's blogdown. Welcome. 

This blog will focus on R, statistics, and public policy. There won't be any VCU basketball. OK, there will be some VCU basketball, but only if it relates to  R, statistics, or public policy.

Here are the *current* principles of the blog: 

* I will strive to be unrelentingly positive. 
* Posts will be short and frequent like [Marginal Revolution](https://marginalrevolution.com/). 
* I will recommend lots of content. 
* I'm going to beg some friends to write guest posts. 
* There will be code. 
